/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import napakalaki.BadStuff;
import napakalaki.TreasureKind;

/**
 *
 * @author jose
 */
public class BadStuffView extends javax.swing.JPanel {
    private BadStuff budStuffModel;
    /**
     * Creates new form BadStuffView
     */
    public BadStuffView() {
        initComponents();
    }
    
    public void setBadStuff(BadStuff bs){
        budStuffModel = bs;
        String mensaje= "";
        
        tspecificvisible.setText(""); //Vacio el contenido inicial
        tspecifichidden.setText(""); //Vacio el contenido actual
        
        
        if (budStuffModel.getnHiddenTreasures() == 99)
            mensaje = "Todos";
        else
            mensaje = budStuffModel.getnHiddenTreasures() + "";
        nhidden.setText(mensaje);
        
        if (budStuffModel.getnVisibleTreasures() == 99)
            mensaje = "Todos";
        else
            mensaje = budStuffModel.getnVisibleTreasures() + "";
        nvisible.setText(mensaje);
        
        if (budStuffModel.getSpecificVisibleTreasures().size() > 0){
             
            for (TreasureKind tk: budStuffModel.getSpecificVisibleTreasures()){
                tspecificvisible.setText(tspecificvisible.getText() + tk.toString() + "\n");
            }
        }
        
        if (budStuffModel.getSpecificHiddenTreasures().size() > 0){
            
            for (TreasureKind tk: budStuffModel.getSpecificHiddenTreasures()){
                tspecifichidden.setText(tspecifichidden.getText() + tk.toString() + "\n" );
            }
        }
       
        // bs.
        /*private javax.swing.JLabel nvisible;
        private javax.swing.JLabel tituloBadStuff;
        private javax.swing.JLabel tspecific;*/
        
        
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        tituloBadStuff = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nhidden = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nvisible = new javax.swing.JLabel();
        tspecificvisible = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tspecifichidden = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        tituloBadStuff.setText("Mal rollo! Descarta:");

        jLabel2.setText("Tesoros ocultos:");

        nhidden.setText("0");

        jLabel5.setText("Tesoros visibles:");

        jLabel6.setText("Especificos visibles:");

        nvisible.setText("0");

        tspecificvisible.setText("-");

        jLabel1.setText("Especificos ocultos:");

        tspecifichidden.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tituloBadStuff)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nhidden)
                            .addComponent(nvisible)))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tspecifichidden)
                            .addComponent(tspecificvisible))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloBadStuff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nhidden)
                        .addGap(10, 10, 10)))
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nvisible))
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tspecificvisible)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tspecifichidden)
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nhidden;
    private javax.swing.JLabel nvisible;
    private javax.swing.JLabel tituloBadStuff;
    private javax.swing.JLabel tspecifichidden;
    private javax.swing.JLabel tspecificvisible;
    // End of variables declaration//GEN-END:variables
}
