/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.awt.Color;
import napakalaki.Treasure;

/**
 *
 * @author jose
 */
public class TreasureView extends javax.swing.JPanel {
    private Treasure treasureModel;
    private boolean selected = false;
    
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }
    public boolean isSelected()
    {
        return selected;
    }
    public Treasure getTreasure()
    {
        return treasureModel;
    }
    public void setTreasure (Treasure t) {
        treasureModel = t;
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/TESOROS/"+t.getName()+".jpg"))); // NOI18N
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccion = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(112, 191));
        setMinimumSize(new java.awt.Dimension(112, 191));
        setPreferredSize(new java.awt.Dimension(112, 191));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seleccion.setMaximumSize(new java.awt.Dimension(112, 191));
        add(seleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 112, 191));

        imagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagenMouseClicked(evt);
            }
        });
        add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 112, 191));
    }// </editor-fold>//GEN-END:initComponents

    private void imagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenMouseClicked
        if(this.selected){
            this.selected = false;            
            seleccion.setOpaque(false);
        }
        else{
            this.selected = true;
            seleccion.setOpaque(true);
            seleccion.setBackground(new Color(0,255,0,100));
        }
        repaint();
    }//GEN-LAST:event_imagenMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel seleccion;
    // End of variables declaration//GEN-END:variables
}
